plugins {
    id 'foshol.java-conventions'
    id 'java-library'
}

def catalogs = extensions.getByType(org.gradle.api.artifacts.VersionCatalogsExtension)
def libs = catalogs.named('libs')

dependencies {
    implementation platform(libs.findLibrary('spring-boot-dependencies').get())
    implementation platform(libs.findLibrary('spring-modulith-bom').get())
}
