plugins {
    id 'foshol.module-conventions'
}

dependencies {
    implementation libs.pgvector
    implementation 'org.postgresql:postgresql'
    implementation 'org.springframework.security:spring-security-core'
    testImplementation 'org.springframework.boot:spring-boot-starter-flyway'
    testRuntimeOnly 'org.flywaydb:flyway-database-postgresql'
}

tasks.withType(Test).configureEach {
    systemProperty 'foshol.flyway.dir',
            rootProject.layout.projectDirectory.dir('app/src/main/resources/db/migration').asFile.absolutePath
}
