package com.rootcause.foshol.review.application.query;

import com.rootcause.foshol.common.enums.AiMode;
import com.rootcause.foshol.common.enums.CaseStatus;
import com.rootcause.foshol.common.enums.CropQuantityUnit;
import com.rootcause.foshol.common.enums.DecisionPath;
import com.rootcause.foshol.common.enums.FieldAreaUnit;
import com.rootcause.foshol.common.enums.MetricsSource;
import com.rootcause.foshol.common.enums.ReviewState;
import com.rootcause.foshol.common.events.CandidateView;
import com.rootcause.foshol.common.events.CaseAudioRef;
import com.rootcause.foshol.common.events.CaseImageRef;
import com.rootcause.foshol.common.events.SymptomView;
import com.rootcause.foshol.review.api.AdvisoryView;
import com.rootcause.foshol.review.api.RemedyRefView;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record ReviewTaskDetailView(
        UUID caseId,
        UUID reviewTaskId,
        String farmerName,
        String cropCode,
        String cropNameBn,
        String cropNameEn,
        boolean cropNameEnFallback,
        String districtCode,
        DecisionPath decisionPath,
        UUID topDiseaseId,
        String topDiseaseNameBn,
        String topDiseaseNameEn,
        boolean topDiseaseNameEnFallback,
        BigDecimal topConfidence,
        int imageCount,
        boolean hasAudio,
        AiMode analysisMode,
        ReviewState state,
        UUID officerId,
        boolean isResubmission,
        short requeueCount,
        Instant submittedAt,
        Instant slaDueAt,
        Instant assignmentDueAt,
        Instant resolutionDueAt,
        BigDecimal top1Confidence,
        BigDecimal top2Confidence,
        BigDecimal margin,
        List<CandidateView> candidates,
        List<SymptomView> symptoms,
        String transcriptBn,
        BigDecimal asrConfidence,
        String gradcamObjectKey,
        boolean hasGradcam,
        List<CaseImageRef> images,
        CaseAudioRef audio,
        UUID parentCaseId,
        List<RemedyRefView> suggestedRemedies,
        UUID suggestedDiseaseId,
        UUID claimedBy,
        Instant claimedAt,
        Instant claimExpiresAt,
        AdvisoryView publishedAdvisory,
        int version,
        UUID cropId,
        CaseStatus caseStatus,
        String noteBn,
        BigDecimal fieldArea,
        FieldAreaUnit fieldAreaUnit,
        BigDecimal cropQuantity,
        CropQuantityUnit cropQuantityUnit,
        MetricsSource metricsSource,
        List<String> unmappedLabels,
        String visionModelId,
        String visionModelVersion,
        int latencyMs,
        String errorCode,
        String officerName) {}
