plugins {
    id 'foshol.java-conventions'
    id 'java-library'
}

dependencies {
    api libs.uuid.creator
    api libs.slf4j.api
    api platform(libs.spring.modulith.bom)
    api platform(libs.spring.boot.dependencies)
    api 'org.springframework.modulith:spring-modulith-api'
    api 'org.springframework:spring-beans'
    testImplementation platform(libs.spring.boot.dependencies)
    testRuntimeOnly platform(libs.spring.boot.dependencies)
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testRuntimeOnly 'ch.qos.logback:logback-classic'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
