#!/usr/bin/env python3
"""Generate historical demo cases. Day-1 stub: does not invent agronomic content.

Full behaviour (SIDECAR-FR-100…107) needs:
- a live API / MinIO for image upload under intake object-key conventions
- V100 demo identities already applied (A1)
- human-authored disease and remedy rows (V11, V15) referenced only by natural-key subselect

This stub validates `--count` / `--seed`, writes a deterministic SQL comment file, and
refuses to emit disease names, dosages, Bangla symptom phrases, or identity rows.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "tools" / "out" / "V101__seed_historical_cases.sql"
MIN_COUNT = 40
MAX_COUNT = 60


def render_sql(*, count: int, seed: int) -> str:
    return (
        "-- Generated by tools/seed_cases.py (Day-1 stub). Deterministic for a given --seed.\n"
        f"-- count={count} seed={seed}\n"
        "--\n"
        "-- This file is NOT a loadable migration. Agent A7 must not write under app/.\n"
        "-- Hand the finished SQL to A1 to place as app/src/main/resources/db/seed/V101__seed_historical_cases.sql.\n"
        "--\n"
        "-- Blocked on a live API + MinIO (SIDECAR-FR-101) and on human-authored knowledge rows.\n"
        "-- Farmers and officers MUST be referenced by INSERT … SELECT against V100 natural keys.\n"
        "-- Diseases and remedies MUST be referenced by INSERT … SELECT against their natural keys.\n"
        "-- No literal UUID for farmer, officer, disease or remedy will be emitted.\n"
        "-- diagnosis_case.note_bn, case_audio.transcript_bn and advisory.officer_note_bn stay NULL\n"
        "-- unless a human-supplied --notes file is provided (SIDECAR-FR-104).\n"
        "-- This stub does not insert identity rows (SIDECAR-FR-107).\n"
        "-- This stub does not author agronomic content (COMMON-CON-003).\n"
        "\n"
        "SELECT 1; -- placeholder; replace after live API + content-owner artefacts exist\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate historical demo-case SQL (stub).")
    parser.add_argument("--count", type=int, required=True)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--notes", type=Path, default=None, help="Human-supplied Bangla notes; unused by the stub.")
    args = parser.parse_args(argv)

    if args.count < MIN_COUNT or args.count > MAX_COUNT:
        print(f"--count must be between {MIN_COUNT} and {MAX_COUNT}", file=sys.stderr)
        return 1

    sql = render_sql(count=args.count, seed=args.seed)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(sql, encoding="utf-8")
    print(f"wrote stub SQL to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
